org: dsahu1997
service: ronweasley-backend

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
  config: file(./secret.json)

provider:
  name: aws
  runtime: python3.8
  stage: prod
  region: ${${self:custom.config}:REGION_NAME}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["PostTable", "Arn"] }
  environment:
    REGION_NAME: ${${self:custom.config}:REGION_NAME}
    POST_TABLE: ${${self:custom.config}:POST_TABLE}
    JWT_SECRET_KEY: ${${self:custom.config}:JWT_SECRET_KEY}
    ADMIN_USERNAME: ${${self:custom.config}:ADMIN_USERNAME}
    ADMIN_PASSWORD: ${${self:custom.config}:ADMIN_PASSWORD}
    BUCKET_NAME: ${${self:custom.config}:BUCKET_NAME}

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"

package:
  exclude:
    - this_project/**
    - __pycache__/**

resources:
  Resources:
    PostTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: ${${self:custom.config}:POST_TABLE}
        AttributeDefinitions:
          - AttributeName: post_type
            AttributeType: S
          - AttributeName: post_id
            AttributeType: S
        KeySchema:
          - AttributeName: post_type
            KeyType: HASH
          - AttributeName: post_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
