org: dsahu1997
service: ronweasley-backend

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
  config: file(./secret.json)

provider:
  name: aws
  runtime: python3.8
  stage: prod
  region: ${${self:custom.config}:REGION_NAME}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:CreateTable
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/*"
    - Effect: "Allow"
      Action:
        - dynamodb:Query
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/*/index/*"
  environment:
    REGION_NAME: ${${self:custom.config}:REGION_NAME}
    POST_TABLE: ${${self:custom.config}:POST_TABLE}

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"

package:
  exclude:
    - this_project/**
    - __pycache__/**

resources:
  Resources:
    POSTTABLE:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: post_type
            AttributeType: S
          - AttributeName: post_id
            AttributeType: S
        KeySchema:
          - AttributeName: post_type
            KeyType: HASH
          - AttributeName: post_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
